
// supported mimetype icons
// keep in sync with frontend/public/mime-types
const mimeIcons = {
    'application-x-generic': 'application-x-generic.svg',
    'audio-x-generic': 'audio-x-generic.svg',
    'font-x-generic': 'font-x-generic.svg',
    'image-x-generic': 'image-x-generic.svg',
    'text-x-generic': 'text-x-generic.svg',
    'video-x-generic': 'video-x-generic.svg',
    'model-x-generic': 'model.svg',

    'inode-directory': 'inode-directory.svg',
    'inode-symlink': 'inode-symlink.svg',

    'application-x-executable': 'application-x-executable.svg',
    'application-x-lx-executable': 'application-x-executable.svg',
    'application-x-ms-ne-executable': 'application-x-executable.svg',
    'application-x-pie-executable': 'application-x-executable.svg',
    'application-vnd.microsoft.portable-executable': 'application-x-executable.svg',
    'application-x-nintendo-3ds-executable': 'application-x-executable.svg',
    'application-x-iso9660-appimage': 'application-x-executable.svg',
    'application-x-python-bytecode': 'application-x-executable.svg',

    'application-x-sharedlib': 'application-x-sharedlib.svg',
    'application-x-pie-sharedlib': 'application-x-sharedlib.svg',
    'application-x-shared-library-la': 'application-x-sharedlib.svg',

    'application-vnd.efi.img': 'application-x-firmware.svg',
    'application-vnd.efi.iso': 'application-x-firmware.svg',
    'text-x-hex': 'application-x-firmware.svg',

    'application-x-xpinstall': 'application-x-addon.svg',
    'application-vnd.openofficeorg.extension': 'application-x-addon.svg',

    'application-pgp-encrypted': 'application-certificate.svg',
    'application-pgp-keys': 'application-certificate.svg',
    'application-pgp-signature': 'application-certificate.svg',
    'application-pkcs7-mime': 'application-certificate.svg',
    'application-pkcs7-signature': 'application-certificate.svg',
    'application-pkcs8': 'application-certificate.svg',
    'application-pkcs8-encrypted': 'application-certificate.svg',
    'application-pkcs10': 'application-certificate.svg',
    'application-pkcs12': 'application-certificate.svg',
    'application-pkix-cert': 'application-certificate.svg',
    'application-pkix-crl': 'application-certificate.svg',
    'application-x-java-jce-keystore': 'application-certificate.svg',
    'application-x-java-keystore': 'application-certificate.svg',
    'application-x-pem-key': 'application-certificate.svg',
    'application-x-pkcs12': 'application-certificate.svg',
    'application-x-pkcs7-certificates': 'application-certificate.svg',
    'application-x-x509-ca-cert': 'application-certificate.svg',
    'application-x-x509-user-cert': 'application-certificate.svg',
    'text-x-ssh-public-key': 'application-certificate.svg',

    'application-zip': 'package-x-generic.svg',
    'application-gzip': 'package-x-generic.svg',
    'application-vnd.rar': 'package-x-generic.svg',
    'application-vnd.debian.binary-package': 'package-x-generic.svg',
    'application-vnd.android.package-archive': 'package-x-generic.svg',
    'application-vnd.ms-cab-compressed': 'package-x-generic.svg',
    'application-vnd.emusic-emusic_package': 'package-x-generic.svg',
    'application-vnd.kde.fontspackage': 'package-x-generic.svg',
    'application-vnd.kde.okular-archive': 'package-x-generic.svg',
    'application-vnd.ipld.car': 'package-x-generic.svg',
    'application-x-7z-compressed': 'package-x-generic.svg',
    'application-x-ace': 'package-x-generic.svg',
    'application-x-alpine-package-keeper-package': 'package-x-generic.svg',
    'application-x-apple-diskimage': 'package-x-generic.svg',
    'application-x-archive': 'package-x-generic.svg',
    'application-x-arj': 'package-x-generic.svg',
    'application-x-asar': 'package-x-generic.svg',
    'application-x-bcpio': 'package-x-generic.svg',
    'application-x-brotli-compressed-tar': 'package-x-generic.svg',
    'application-x-bzip1': 'package-x-generic.svg',
    'application-x-bzip1-compressed-tar': 'package-x-generic.svg',
    'application-x-bzip2': 'package-x-generic.svg',
    'application-x-bzip2-compressed-tar': 'package-x-generic.svg',
    'application-x-bzip3-compressed-tar': 'package-x-generic.svg',
    'application-x-cd-image': 'package-x-generic.svg',
    'application-x-compress': 'package-x-generic.svg',
    'application-x-compressed-iso': 'package-x-generic.svg',
    'application-x-compressed-tar': 'package-x-generic.svg',
    'application-x-cpio': 'package-x-generic.svg',
    'application-x-cpio-compressed': 'package-x-generic.svg',
    'application-x-dar': 'package-x-generic.svg',
    'application-x-deb': 'package-x-generic.svg',
    'application-x-discjuggler-cd-image': 'package-x-generic.svg',
    'application-x-lha': 'package-x-generic.svg',
    'application-x-lrzip': 'package-x-generic.svg',
    'application-x-lrzip-compressed-tar': 'package-x-generic.svg',
    'application-x-lz4-compressed-tar': 'package-x-generic.svg',
    'application-x-lzip': 'package-x-generic.svg',
    'application-x-lzip-compressed-tar': 'package-x-generic.svg',
    'application-x-lzma': 'package-x-generic.svg',
    'application-x-lzma-compressed-tar': 'package-x-generic.svg',
    'application-x-lzop': 'package-x-generic.svg',
    'application-x-mimearchive': 'package-x-generic.svg',
    'application-x-qemu-disk': 'package-x-generic.svg',
    'application-x-rar': 'package-x-generic.svg',
    'application-x-raw-disk-image': 'package-x-generic.svg',
    'application-x-raw-disk-image-xz-compressed': 'package-x-generic.svg',
    'application-x-raw-floppy-disk-image': 'package-x-generic.svg',
    'application-x-rpm': 'package-x-generic.svg',
    'application-x-rzip': 'package-x-generic.svg',
    'application-x-rzip-compressed-tar': 'package-x-generic.svg',
    'application-x-shar': 'package-x-generic.svg',
    'application-x-sv4cpio': 'package-x-generic.svg',
    'application-x-tar': 'package-x-generic.svg',
    'application-x-tarz': 'package-x-generic.svg',
    'application-x-ustar': 'package-x-generic.svg',
    'application-x-vdi-disk': 'package-x-generic.svg',
    'application-x-vhd-disk': 'package-x-generic.svg',
    'application-x-vhdx-disk': 'package-x-generic.svg',
    'application-x-vmdk-disk': 'package-x-generic.svg',
    'application-x-xar': 'package-x-generic.svg',
    'application-x-xz': 'package-x-generic.svg',
    'application-x-xz-compressed-tar': 'package-x-generic.svg',
    'application-x-zoo': 'package-x-generic.svg',
    'application-x-zstd-compressed-tar': 'package-x-generic.svg',

    'application-x-source-rpm': 'x-package-repository.svg',

    'text-html': 'text-html.svg',
    'application-xhtml+xml': 'text-html.svg',

    'application-msword': 'x-office-document.svg',
    'application-pdf': 'x-office-document.svg',
    'application-rtf': 'x-office-document.svg',
    'application-vnd.lotus-wordpro': 'x-office-document.svg',
    'application-vnd.ms-word': 'x-office-document.svg',
    'application-vnd.ms-word.document.macroEnabled.12': 'x-office-document.svg',
    'application-vnd.oasis.opendocument.text': 'x-office-document.svg',
    'application-vnd.oasis.opendocument.text-flat-xml': 'x-office-document.svg',
    'application-vnd.oasis.opendocument.text-web': 'x-office-document.svg',
    'application-vnd.openxmlformats-officedocument.wordprocessingml.document': 'x-office-document.svg',
    'application-vnd.stardivision.writer': 'x-office-document.svg',
    'application-vnd.stardivision.writer-global': 'x-office-document.svg',
    'application-vnd.sun.xml.writer': 'x-office-document.svg',
    'application-vnd.sun.xml.writer.global': 'x-office-document.svg',
    'application-vnd.wordperfect': 'x-office-document.svg',
    'application-x-abiword': 'x-office-document.svg',
    'application-x-applix-word': 'x-office-document.svg',
    'application-x-bzpdf': 'x-office-document.svg',
    'application-x-gzpdf': 'x-office-document.svg',
    'application-x-kword': 'x-office-document.svg',
    'application-x-lzpdf': 'x-office-document.svg',
    'application-x-pocket-word': 'x-office-document.svg',
    'application-x-xzpdf': 'x-office-document.svg',
    'text-richtext': 'x-office-document.svg',
    'text-rtf': 'x-office-document.svg',

    'application-msword-template': 'x-office-document-template.svg',
    'application-vnd.ms-word.template.macroEnabled.12': 'x-office-document-template.svg',
    'application-vnd.oasis.opendocument.text-master': 'x-office-document-template.svg',
    'application-vnd.oasis.opendocument.text-master-template': 'x-office-document-template.svg',
    'application-vnd.oasis.opendocument.text-template': 'x-office-document-template.svg',
    'application-vnd.openxmlformats-officedocument.wordprocessingml.template': 'x-office-document-template.svg',
    'application-vnd.sun.xml.writer.template': 'x-office-document-template.svg',

    'application-vnd.ms-excel': 'x-office-spreadsheet.svg',
    'application-vnd.ms-excel.addin.macroEnabled.12': 'x-office-spreadsheet.svg',
    'application-vnd.ms-excel.sheet.binary.macroEnabled.12': 'x-office-spreadsheet.svg',
    'application-vnd.ms-excel.sheet.macroEnabled.12': 'x-office-spreadsheet.svg',
    'application-vnd.oasis.opendocument.spreadsheet': 'x-office-spreadsheet.svg',
    'application-vnd.oasis.opendocument.spreadsheet-flat-xml': 'x-office-spreadsheet.svg',
    'application-vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'x-office-spreadsheet.svg',
    'application-vnd.stardivision.calc': 'x-office-spreadsheet.svg',
    'application-vnd.sun.xml.calc': 'x-office-spreadsheet.svg',
    'application-x-applix-spreadsheet': 'x-office-spreadsheet.svg',
    'application-x-gnumeric': 'x-office-spreadsheet.svg',
    'application-x-pyspread-bz-spreadsheet': 'x-office-spreadsheet.svg',
    'application-x-pyspread-spreadsheet': 'x-office-spreadsheet.svg',
    'application-x-starcalc': 'x-office-spreadsheet.svg',
    'text-csv': 'x-office-spreadsheet.svg',
    'text-csv-schema': 'x-office-spreadsheet.svg',
    'text-tab-separated-values': 'x-office-spreadsheet.svg',

    'application-vnd.ms-excel.template.macroEnabled.12': 'x-office-spreadsheet-template.svg',
    'application-vnd.oasis.opendocument.spreadsheet-template': 'x-office-spreadsheet-template.svg',
    'application-vnd.openxmlformats-officedocument.spreadsheetml.template': 'x-office-spreadsheet-template.svg',
    'application-vnd.sun.xml.calc.template': 'x-office-spreadsheet-template.svg',

    'application-vnd.apple.keynote': 'x-office-presentation.svg',
    'application-vnd.ms-powerpoint': 'x-office-presentation.svg',
    'application-vnd.ms-powerpoint.addin.macroEnabled.12': 'x-office-presentation.svg',
    'application-vnd.ms-powerpoint.presentation.macroEnabled.12': 'x-office-presentation.svg',
    'application-vnd.ms-powerpoint.slide.macroEnabled.12': 'x-office-presentation.svg',
    'application-vnd.ms-powerpoint.slideshow.macroEnabled.12': 'x-office-presentation.svg',
    'application-vnd.oasis.opendocument.presentation': 'x-office-presentation.svg',
    'application-vnd.oasis.opendocument.presentation-flat-xml': 'x-office-presentation.svg',
    'application-vnd.openxmlformats-officedocument.presentationml.presentation': 'x-office-presentation.svg',
    'application-vnd.openxmlformats-officedocument.presentationml.slide': 'x-office-presentation.svg',
    'application-vnd.openxmlformats-officedocument.presentationml.slideshow': 'x-office-presentation.svg',
    'application-vnd.stardivision.impress': 'x-office-presentation.svg',
    'application-vnd.stardivision.impress-packed': 'x-office-presentation.svg',
    'application-vnd.sun.xml.impress': 'x-office-presentation.svg',
    'application-x-starimpress': 'x-office-presentation.svg',

    'application-vnd.ms-powerpoint.template.macroEnabled.12': 'x-office-presentation-template.svg',
    'application-vnd.oasis.opendocument.presentation-template': 'x-office-presentation-template.svg',
    'application-vnd.openxmlformats-officedocument.presentationml.template': 'x-office-presentation-template.svg',
    'application-vnd.sun.xml.impress.template': 'x-office-presentation-template.svg',

    'application-vnd.ms-visio': 'x-office-drawing.svg',
    'application-vnd.ms-visio.drawing.macroEnabled.main+xml': 'x-office-drawing.svg',
    'application-vnd.ms-visio.drawing.main+xml': 'x-office-drawing.svg',
    'application-vnd.ms-visio.stencil.macroEnabled.main+xml': 'x-office-drawing.svg',
    'application-vnd.ms-visio.stencil.main+xml': 'x-office-drawing.svg',
    'application-vnd.ms-visio.template.macroEnabled.main+xml': 'x-office-drawing.svg',
    'application-vnd.ms-visio.template.main+xml': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.chart': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.chart-template': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.formula': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.formula-template': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.graphics': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.graphics-flat-xml': 'x-office-drawing.svg',
    'application-vnd.oasis.opendocument.graphics-template': 'x-office-drawing.svg',
    'application-vnd.stardivision.chart': 'x-office-drawing.svg',
    'application-vnd.stardivision.draw': 'x-office-drawing.svg',
    'application-vnd.stardivision.math': 'x-office-drawing.svg',
    'application-vnd.sun.xml.draw': 'x-office-drawing.svg',
    'application-vnd.sun.xml.draw.template': 'x-office-drawing.svg',
    'application-vnd.sun.xml.math': 'x-office-drawing.svg',
    'application-x-stardraw': 'x-office-drawing.svg',
    'application-x-starmath': 'x-office-drawing.svg',

    'text-vcard': 'x-office-addressbook.svg',
    'text-x-vcard': 'x-office-addressbook.svg',
    'text-directory': 'x-office-addressbook.svg',

    'application-ecmascript': 'text-x-script.svg',
    'application-javascript': 'text-x-script.svg',
    'application-typescript': 'text-x-script.svg',
    'application-x-fishscript': 'text-x-script.svg',
    'application-x-gdscript': 'text-x-script.svg',
    'application-x-javascript': 'text-x-script.svg',
    'application-x-nuscript': 'text-x-script.svg',
    'application-x-perl': 'text-x-script.svg',
    'application-x-php': 'text-x-script.svg',
    'application-x-powershell': 'text-x-script.svg',
    'application-x-ruby': 'text-x-script.svg',
    'application-x-shellscript': 'text-x-script.svg',
    'text-javascript': 'text-x-script.svg',
    'text-jscript.encode': 'text-x-script.svg',
    'text-scriptlet': 'text-x-script.svg',
    'text-tcl': 'text-x-script.svg',
    'text-vbscript': 'text-x-script.svg',
    'text-vbscript.encode': 'text-x-script.svg',
    'text-x-awk': 'text-x-script.svg',
    'text-x-basic': 'text-x-script.svg',
    'text-x-csh': 'text-x-script.svg',
    'text-x-gawk': 'text-x-script.svg',
    'text-x-lua': 'text-x-script.svg',
    'text-x-nawk': 'text-x-script.svg',
    'text-x-perl': 'text-x-script.svg',
    'text-x-php': 'text-x-script.svg',
    'text-x-python': 'text-x-script.svg',
    'text-x-python2': 'text-x-script.svg',
    'text-x-python3': 'text-x-script.svg',
    'text-x-ruby': 'text-x-script.svg',
    'text-x-sed': 'text-x-script.svg',
    'text-x-shellscript': 'text-x-script.svg',
    'text-x-tcl': 'text-x-script.svg',
    'text-x-vb': 'text-x-script.svg'
};

function getMimeIcon(mimeType) {
    if (!mimeType) return mimeIcons['application-x-generic'];

    const mime = mimeType.split('/');

    if (mimeIcons[mime[0] + '-' + mime[1]]) return mimeIcons[mime[0] + '-' + mime[1]];
    if (mimeIcons[mime[0] + '-x-generic']) return mimeIcons[mime[0] + '-x-generic'];

    return mimeIcons['application-x-generic'];
}

export {
    getMimeIcon
};

export default {
    mimeIcons,
    getMimeIcon
};
